// ============================================================
// Stage3〜10 汎用手順ステージ定義(手順書 Step17〜66のゲーム化)
// steps: 実施すべき確認項目(順不同で選べるが needs で順序制約)
//   needs: 先にやらないと実行できない(ハードブロック)
//   softNeeds: 飛ばすと軽ミスになる
//   defect: この操作で発見できる不良タイプ
// dangers: いつでも選べる危険な操作
// ============================================================
const GENERIC_STAGES = {
  stage3: {
    initial: { sourceOn: true, mainOn: true, cps: { CP1: true, CP2: true, CP3: true } },
    defectCountRange: [0, 2],
    fireAt: "panel",

    // ---- 調べる: 情報を見るだけ。一致/不一致の判断はプレイヤーがやる ----
    inspects: [
      { id: "i_cpu", station: "machine", label: "PLC本体の銘板を見る", modelId: "i_cpu",
        text: `<span class="lbl">MITSUBISHI MELSEC-Q</span>
<span class="lbl">CPU UNIT</span>
<span class="lbl">MODEL </span><span class="val">Q06UDVCPU</span>
<span class="lbl">SERIAL </span>2410 0871
<span class="lbl">電源ユニット </span>Q62P` },
      { id: "i_units", station: "machine", label: "増設ユニットの並びを見る", modelId: "i_units",
        text: `<span class="lbl">ベースユニット Q35B(5スロット)</span>
 <span class="lbl">スロット0:</span> <span class="val">QX40</span>(DC入力16点)
 <span class="lbl">スロット1:</span> <span class="val">QX40</span>(DC入力16点)
 <span class="lbl">スロット2:</span> <span class="val">QY40P</span>(トランジスタ出力16点)
 <span class="lbl">スロット3:</span> <span class="val">QJ71C24N</span>(シリアル通信)
 <span class="lbl">スロット4:</span> 空き` },
      { id: "i_proj", station: "pc", label: "GX Works2のプロジェクト情報を見る", modelId: "i_proj",
        text: `<span class="lbl">プロジェクト名 </span>JISSHU_2024.gxw
<span class="lbl">PLCシリーズ </span>QCPU(Qモード)
<span class="lbl">PLCタイプ </span><span class="val">Q06UDV</span>
<span class="lbl">最終更新 </span>2024/10/03 16:22` },
      { id: "i_io", station: "pc", label: "GX Works2のI/O割付設定を見る", modelId: "i_io",
        text: `<span class="lbl">I/O割付設定</span>
 <span class="lbl">スロット0:</span> 入力16点 先頭XY <span class="val">0000</span>
 <span class="lbl">スロット1:</span> 入力16点 先頭XY <span class="val">0010</span>
 <span class="lbl">スロット2:</span> 出力16点 先頭XY <span class="val">0020</span>
 <span class="lbl">スロット3:</span> インテリ 先頭XY <span class="val">0030</span>` },
      { id: "i_conn", station: "pc", label: "接続先設定の画面を見る", modelId: "i_conn",
        text: `<span class="lbl">パソコン側I/F </span><span class="val">シリアル/USB</span>
<span class="lbl">　　詳細設定 </span><span class="val">USB</span>
<span class="lbl">シーケンサ側I/F </span><span class="val">CPUユニット</span>
<span class="lbl">他局指定 </span><span class="val">他局指定なし</span>` },
      { id: "i_diag", station: "pc", label: "PLC診断の画面を見る", modelId: "i_diag",
        text: `<span class="lbl">PLC診断</span>
 CPUエラー   : <span class="val">なし</span>
 I/Oユニット : <span class="val">正常</span>
 ネットワーク: <span class="val">正常</span>
 バッテリ    : <span class="val">正常</span>
 <span class="lbl">RUN/STOPスイッチ: STOP</span>` },
    ],

    // ---- 照合して判断する: 答えは選択肢に書かない ----
    judges: [
      { id: "j_cpu", station: "pc", label: "PLCの型式が合っているか判断する",
        needsInspect: ["i_cpu", "i_proj"],
        question: "実機のCPUと、開いているプロジェクトのPLCタイプ。この2つは合っているか?",
        options: [
          { id: "ok", label: "一致している。このまま進めてよい" },
          { id: "ng", label: "違っている。書き込んではいけない" },
        ],
        answerOK: "ok", answerNG: "ng",
        okMsg: "実機Q06UDV、プロジェクトQ06UDV。一致だ。ヨシ!",
        missText: "型式が違うのに『一致』と判断して先に進んだ",
        falseText: "型式は一致しているのに『違う』と判断した",
        falseDesc: "PLC型式の照合で誤判断(実際は一致)",
        comment: "間違ったPLCに書き込まないための最初の関門(Step17)。" },

      { id: "j_io", station: "pc", label: "I/O割付が図面と合っているか判断する",
        needsInspect: ["i_units", "i_io"],
        question: "実機のユニットの並びと、GX Works2のI/O割付。図面のI/O表(スロット0=X00〜、1=X10〜、2=Y20〜、3=先頭30)と見比べて、どうか?",
        options: [
          { id: "ok", label: "実機・設定・図面すべて一致している" },
          { id: "ng", label: "どこかがズレている。直す必要がある" },
        ],
        answerOK: "ok", answerNG: "ng",
        okMsg: "ユニットの並びも先頭XYも図面どおり。一致だ。",
        missText: "I/O割付がズレているのに『一致』と判断して先に進んだ",
        falseText: "I/O割付は合っているのに『ズレている』と判断した",
        falseDesc: "I/O割付の照合で誤判断(実際は一致)",
        comment: "割付がズレると以降のI/Oチェックが全部狂う(Step20)。" },

      { id: "j_diag", station: "pc", label: "PLC診断の結果を判断する",
        needsInspect: ["i_diag"], needs: ["s_write"],
        question: "診断画面を見た。この装置は次の工程へ進んでよい状態か?",
        options: [
          { id: "ok", label: "異常なし。次工程へ進んでよい" },
          { id: "ng", label: "異常がある。記録して対処が必要だ" },
        ],
        answerOK: "ok", answerNG: "ng", checkpoint: true,
        okMsg: "CPU・I/O・ネットワーク・バッテリすべて正常。RUNにして次工程へ!",
        missText: "診断にエラーが出ているのに『異常なし』と判断した",
        falseText: "診断は正常なのに『異常あり』と判断した",
        falseDesc: "PLC診断で誤判断(実際は正常)",
        comment: "書き込めても診断エラーが残っていたら次工程へ進まない(Step24)。" },
    ],

    // ---- 操作(答えを選択肢に書かない、操作単位に分解) ----
    steps: [
      { id: "s_conn", station: "pc", label: "接続先設定を開いて設定する", needsInspect: ["i_conn"],
        comment: "USBケーブルを挿しただけでは通信できない(Step18)。",
        doneMsg: "PC側I/F=シリアル/USB、シーケンサ側=CPUユニット。設定を保存した。" },
      { id: "s_test", station: "pc", label: "通信テストを実行する", needs: ["s_conn"], defect: "commfail",
        comment: "書き込み前に必ず接続確認(Step19)。",
        doneMsg: "『接続に成功しました』。通信OK!" },
      { id: "s_backup", station: "pc", label: "既存プログラムを読み出して保存する",
        comment: "書き込み前のバックアップは保険(Step23)。",
        doneMsg: "読み出してバックアップ保存した。これで何かあっても戻せる。" },
      { id: "s_write", station: "pc", label: "プログラムとパラメータを書き込む",
        needs: ["j_cpu", "s_test"], softNeeds: ["s_backup", "j_io"],
        comment: "対象PLC・書き込み対象を確認してから(Step23)。",
        doneMsg: "書き込み完了。エラーなし。" },
    ],

    dangers: [
      { station: "pc", label: "型式を確認せず、いきなり書き込みボタンを押す", level: "mid",
        text: "接続先がどのPLCか確認しないまま書き込み開始…途中でエラーになり失敗した",
        lesson: "書き込み前に型式照合と通信テスト(Step17・19)。間違ったPLCへの書き込みは装置の誤動作に直結する。" },
      { station: "pc", label: "RUN中のPLCにそのまま書き込む", level: "big",
        text: "動作中のPLCにプログラムを上書き!出力が一瞬暴れて、装置がガシャンと音を立てた!",
        lesson: "稼働中の装置に書き込む場合は必ず停止状態・安全状態を確認してから(Step23)。RUN中の書き込みは予期せぬ出力変化を招く。" },
      { station: "machine", label: "よく分からないがDIPスイッチを動かしてみる", level: "mid",
        text: "設定が変わって通信不能に…慌てて元に戻した",
        lesson: "実機側のスイッチ設定は図面・マニュアルの確認が先。勘で触らない。" },
      { station: "machine", label: "通電したままユニットを抜き差ししてみる", level: "big",
        text: "活線挿抜!バチッと音がしてCPUエラーランプが赤く光った!",
        lesson: "ユニットの抜き差しは必ず電源を落としてから。通電中の抜き差しは機器を壊す。" },
    ],

    // ---- 不良: 「調べた画面」の表示そのものが変わる(教えてもらえない) ----
    defectPool: [
      { type: "cpumismatch", name: "PLC型式の不一致(実機とプロジェクトが別物)",
        judge: "j_cpu", inspect: "i_proj",
        inspectText: `<span class="lbl">プロジェクト名 </span>JISSHU_2023.gxw
<span class="lbl">PLCシリーズ </span>QCPU(Qモード)
<span class="lbl">PLCタイプ </span><span class="val">Q06UDH</span>
<span class="lbl">最終更新 </span>2023/08/11 09:40`,
        lesson: "実機Q06UDVに対しプロジェクトはQ06UDH。型式違いのまま書き込むと動かない・壊す(Step17)。似た型番ほど危ない。",
        correctMsg: "実機はQ06UDV、プロジェクトはQ06UDH。別物だ!書き込む前に気づけてよかった。記録した。" },

      { type: "iomismatch", name: "I/O割付の不一致(先頭XYアドレスのズレ)",
        judge: "j_io", inspect: "i_io",
        inspectText: `<span class="lbl">I/O割付設定</span>
 <span class="lbl">スロット0:</span> 入力16点 先頭XY <span class="val">0000</span>
 <span class="lbl">スロット1:</span> 入力16点 先頭XY <span class="val">0020</span>
 <span class="lbl">スロット2:</span> 出力16点 先頭XY <span class="val">0030</span>
 <span class="lbl">スロット3:</span> インテリ 先頭XY <span class="val">0040</span>`,
        lesson: "スロット1以降の先頭XYが図面と16点ぶんズレている。割付ズレは後工程のI/Oチェック全滅につながる(Step20)。",
        correctMsg: "スロット1が0010のはずが0020。図面とズレている!修正して記録した。" },

      { type: "diagerror", name: "PLCのバッテリエラー残留",
        judge: "j_diag", inspect: "i_diag",
        inspectText: `<span class="lbl">PLC診断</span>
 CPUエラー   : <span class="val">なし</span>
 I/Oユニット : <span class="val">正常</span>
 ネットワーク: <span class="val">正常</span>
 バッテリ    : <span class="val" style="color:#e06060">BATTERY ERROR (1600)</span>
 <span class="lbl">RUN/STOPスイッチ: STOP</span>`,
        lesson: "診断エラーが残ったまま次工程に進まない(Step24)。電池切れは停電時のプログラム消失につながる。",
        correctMsg: "バッテリエラー1600。記録して電池交換を手配した。エラー内容を記録してから対処、だな。" },

      { type: "commfail", name: "USB通信の不通(ドライバ・ケーブル不良)",
        lesson: "通信NGはケーブル・ドライバ・接続先設定の順に切り分ける(Step19)。",
        eventDesc: "通信テスト実行…失敗!『接続先CPUと交信できません』と出た。どうする?",
        correctLabel: "ケーブル・USBポート・接続先設定を順に確認して再テストする",
        correctMsg: "別のUSBポートに挿し直して再テスト…成功!原因を記録した。",
        wrongLabel: "PCを再起動して祈る", wrongLevel: "mid",
        wrongText: "再起動に5分、結果は同じ。祈りは通信仕様書に載っていない…(原因未特定のまま)" },
    ],
  },

  stage4: {
    initial: { sourceOn: true, mainOn: true, cps: { CP1: true, CP2: true, CP3: true } },
    defectCountRange: [0, 2],
    fireAt: "machine",
    steps: [
      { id: "s25", station: "machine", label: "対象機器のIPアドレス・局番を図面と照合する", defect: "ipdup",
        comment: "機器ごとに設定方法が違う。マニュアル必須(Step25)。",
        doneMsg: "ロボコン・リモートI/O・タッチパネル、全て図面どおり。" },
      { id: "s26", station: "machine", label: "機器の電源・通信・エラーランプを確認する", defect: "commlamp",
        comment: "ランプの意味は機器ごとに違う。マニュアルで確認(Step26)。",
        doneMsg: "全機器、電源ランプ点灯・エラーランプ消灯。正常だ。" },
      { id: "s27", station: "pc", label: "PLC側の診断画面で通信状態を確認する", needs: ["s25"],
        comment: "機器側だけでなくPLC側からも見る(Step27)。",
        doneMsg: "CC-Link診断・Ethernet診断とも異常なし。" },
      { id: "s28", station: "pc", label: "全機器がPLCから認識されているか確認する", needs: ["s27"], defect: "unrecognized",
        comment: "1台でも未認識なら、その機器単体を優先確認(Step28)。",
        doneMsg: "GOT・リモートI/O・ロボット、全局交信中!" },
      { id: "s29", station: "machine", label: "設定変更した機器の電源を入れ直し、反映を確認する", needs: ["s25"], checkpoint: true,
        comment: "設定変更は電源再投入で反映される機器が多い(Step29)。",
        doneMsg: "再起動後も通信正常。設定はちゃんと保存されていた。" },
    ],
    dangers: [
      { station: "machine", label: "終端抵抗を試しに外してみる", level: "mid",
        text: "通信が不安定になってエラーが出始めた…慌てて元に戻した",
        lesson: "終端抵抗は信号の反射(ノイズ)を防ぐ部品。理由なく外さない。" },
      { station: "pc", label: "勘で局番を変えて様子を見る", level: "mid",
        text: "別の機器と局番が重複して通信が全滅した…図面を見て元に戻した",
        lesson: "局番・IPアドレスは図面とネットワーク構成図が正。勘で設定を変えない(Step27)。" },
    ],
    defectPool: [
      { type: "ipdup", name: "局番の重複(2台が同じ局番)",
        lesson: "局番・IP重複はネットワーク全体を不安定にする(Step21・25)。",
        eventDesc: "照合していくと…ロボコンとリモートI/Oの局番が両方『3』になっている!",
        correctLabel: "図面どおりに局番を修正して記録する",
        correctMsg: "リモートI/Oを局番4に修正。図面と一致した。記録OK。",
        wrongLabel: "片方は動いてるみたいだし、まあいいか", wrongLevel: "miss" },
      { type: "commlamp", name: "通信ランプの異常点滅",
        lesson: "ランプ表示の意味は機器ごとに違う。マニュアルで確認する(Step26)。",
        eventDesc: "電源ランプは点灯…だがSD/RDランプが見たことのないパターンで点滅している!",
        correctLabel: "マニュアルで点滅パターンの意味を調べ、記録する",
        correctMsg: "『局番設定異常』の点滅パターンだった。記録した。マニュアル様々だ。",
        wrongLabel: "点いてるからヨシ!", wrongLevel: "miss" },
      { type: "unrecognized", name: "1台だけ未認識(コネクタ半挿し)",
        lesson: "一部だけ通信できない時は、その機器単体の設定・配線・電源を優先確認(Step28)。",
        eventDesc: "診断画面…リモートI/Oが1台だけ『未交信』になっている!",
        correctLabel: "その機器のケーブル・コネクタを確認して挿し直し、記録する",
        correctMsg: "コネクタが半挿しだった。カチッと挿し直したら交信開始。記録OK。",
        wrongLabel: "そのうち認識するだろう。待つ", wrongLevel: "miss" },
    ],
  },

  stage5: {
    initial: { sourceOn: true, mainOn: true, cps: { CP1: true, CP2: true, CP3: true } },
    defectCountRange: [0, 2],
    fireAt: "machine",
    steps: [
      { id: "s30", station: "pc", label: "図面のI/O表とPLC入力モニタを照合する(全点)", defect: "wronginput",
        comment: "タッチパネル表示でなくPLCの実入力で確認(Step30)。",
        doneMsg: "入力番号、図面と一致。チェックを付けながら確認した。" },
      { id: "s31a", station: "machine", label: "センサー・スイッチを実際に動かして入力を確認する", needs: ["s30"], defect: "sensorfail",
        comment: "センサーLEDとPLC入力の両方が反応すること(Step31)。",
        doneMsg: "各センサー、動かすとLED点灯+PLC入力ON。反応も正転だ。" },
      { id: "s31b", station: "panel", label: "タッチパネル表示とPLC入力の一致を確認する", needs: ["s30"],
        comment: "画面表示とPLC実入力の両方を見る(Step31)。",
        doneMsg: "タッチパネルのモニタ画面もPLC入力と一致している。" },
      { id: "s31c", station: "desk", label: "確認結果を記録し、配線ミスは連絡リストにまとめる", needs: ["s31a"], checkpoint: true,
        comment: "電装屋に確認してもらえるよう結果を残す(Step30)。",
        doneMsg: "確認結果を記録した。これで引き継ぎもバッチリだ。" },
    ],
    dangers: [
      { station: "pc", label: "反応しない入力をPLC上で強制ONして先へ進む", level: "mid",
        text: "モニタ上はONになった。だが実物のセンサーは死んだまま…何のための確認だ?",
        lesson: "入力チェックは『実物とPLCの一致』を見る工程。強制ONは確認の意味を消してしまう。" },
      { station: "machine", label: "シリンダの隙間に手を入れてセンサーを押す", level: "mid",
        text: "危ない!今日はエアーが無いからいいものの、機械に手を入れる癖は事故のもとだ",
        lesson: "可動部に手を入れない。センサーは治具や工具で押して確認する。" },
    ],
    defectPool: [
      { type: "wronginput", name: "入力番号の入れ違い(X05とX06が逆)",
        lesson: "配線ミスは配線を直すのが筋。図面は装置の戸籍だ(Step30)。",
        eventDesc: "図面ではX05が前進端センサー…だがモニタではX06がONになる!逆だ!",
        correctLabel: "図面と違う箇所を洗い出して記録する(配線修正を依頼)",
        correctMsg: "X05/X06の入れ違いを記録。電装屋への確認リストに追加した。",
        wrongLabel: "ラダー側を書き換えて辻褄を合わせる", wrongLevel: "mid",
        wrongText: "プログラムと図面が食い違う装置が爆誕するところだった…次に触る人が地獄を見るぞ" },
      { type: "sensorfail", name: "センサー配線の断線(LED点灯するが入力が来ない)",
        lesson: "LED点灯=センサーは生きている。疑うべきは配線・入力ユニット側(Step31)。",
        eventDesc: "センサーのLEDは点いている…のにPLCのXがONしない!",
        correctLabel: "センサー〜端子台の配線を疑い、記録する",
        correctMsg: "配線側の問題と切り分けた。記録して修正依頼だ。",
        wrongLabel: "センサーの故障だろう。新品に交換すれば直るはず", wrongLevel: "miss" },
    ],
  },

  stage6: {
    initial: { sourceOn: true, mainOn: true, cps: { CP1: true, CP2: true, CP3: true } },
    defectCountRange: [0, 2],
    fireAt: "machine",
    steps: [
      { id: "s32", station: "panel", label: "非常停止の押下/解除で状態が切り替わるか確認する", defect: "estopcontact",
        comment: "押した状態と解除した状態の両方を確認(Step32)。",
        doneMsg: "押すと遮断、解除で復帰。非常停止の接点は正常だ。" },
      { id: "s33", station: "pc", label: "PLCモニタで非常停止の入力信号を確認する", needs: ["s32"],
        comment: "ランプや画面表示だけでなくPLCの実入力を見る(Step33)。",
        doneMsg: "押下・解除に合わせてPLC入力もきちんと切り替わる。" },
      { id: "s34", station: "machine", label: "サーボ・ロボットが意図せずONしていないことを確認する",
        comment: "運転準備を入れた後に動力が入る可能性を考える(Step34)。",
        doneMsg: "サーボOFF・ロボット停止中。周囲に人も障害物もなし。" },
      { id: "s35", station: "pc", label: "運転準備を妨げるアラームがないか確認する", defect: "alarmstuck",
        comment: "原因を確認せずリセットを繰り返さない(Step35)。",
        doneMsg: "PLC・タッチパネル・サーボ・ロボット、アラームなし。" },
      { id: "s37", station: "pc", label: "ラダーで運転準備条件を1つずつ確認する", needs: ["s35"],
        comment: "どの条件で止まっているかを特定する(Step37)。",
        doneMsg: "非常停止・アラーム・エアー・サーボ…条件は全て成立している。" },
      { id: "s38", station: "panel", label: "周囲の安全を確認して運転準備ONスイッチを押す", needs: ["s32", "s37"], softNeeds: ["s34"], checkpoint: true,
        comment: "操作前に周囲確認。非常停止に手が届く位置で(Step38)。",
        doneMsg: "カチッ。運転準備ランプ点灯!成立だ!" },
      { id: "s39", station: "pc", label: "運転準備ランプとPLC内部信号の両方を確認する", needs: ["s38"],
        comment: "ランプの点灯だけで判断しない(Step39)。",
        doneMsg: "内部信号もON。ランプと一致している。" },
      { id: "s40", station: "machine", label: "ベテラン立会いのもと非常停止の実動作を確認する", needs: ["s38"],
        comment: "非常停止で確実に止まり、解除だけで再起動しないこと(Step40)。",
        doneMsg: "非常停止で即停止、解除後も勝手に再起動しない。完璧だ。" },
    ],
    dangers: [
      { station: "pc", label: "成立しない条件をPLC上で強制ONして運転準備を入れる", level: "big",
        text: "安全に関わる条件を強制ONしたまま、装置が動ける状態になってしまった!",
        lesson: "安全系の条件は絶対に強制ONしない。一時的な無効化は安全に関係しない条件だけ、ベテラン確認のうえで(Step37)。" },
      { station: "panel", label: "アラームをとりあえずリセット連打で消す", level: "mid",
        text: "消えない…原因が残ったままリセットを連打しても無駄だ",
        lesson: "アラームは原因を取り除いてからリセット(Step35〜36)。" },
    ],
    defectPool: [
      { type: "estopcontact", name: "非常停止スイッチの接点不良",
        lesson: "非常停止は命綱。動作しないまま先に進むのは厳禁(Step32〜33)。",
        eventDesc: "非常停止を押しても…信号が変わらない!接点が効いていないようだ!",
        correctLabel: "スイッチの接点・配線を疑い、記録する(装置は動かさない)",
        correctMsg: "接点不良を記録。修理まで運転準備はお預けだ。当然だな。",
        wrongLabel: "たまたまだろう。もう一回押したら直るかも", wrongLevel: "mid",
        wrongText: "非常停止が効かない装置で作業を続けるところだった!ゾッとする話だ" },
      { type: "alarmstuck", name: "解除されないアラーム(サーボ異常の残留)",
        lesson: "原因を確認せずリセットを繰り返さない(Step35)。",
        eventDesc: "アラーム一覧にサーボ異常が残っている…リセットしても消えない!",
        correctLabel: "発生原因を確認し、アラーム内容を記録する",
        correctMsg: "エンコーダケーブルの緩みが原因だった。記録して締め直し依頼。",
        wrongLabel: "電源を入れ直せば消えるだろう", wrongLevel: "miss" },
    ],
  },

  stage7: {
    initial: { sourceOn: true, mainOn: true, cps: { CP1: true, CP2: true, CP3: true } },
    defectCountRange: [0, 2],
    fireAt: "machine",
    steps: [
      { id: "s41", station: "pc", label: "図面の出力番号とPLC出力番号を照合する",
        comment: "出力ON前に、動いても危険がない状態か確認(Step41)。",
        doneMsg: "出力番号、図面のI/O表と一致している。" },
      { id: "s42a", station: "machine", label: "装置内に人がいないこと・周囲の安全を確認する",
        comment: "出力確認は入力確認より危険が高い(Step42)。",
        doneMsg: "装置内・周囲に人なし。非常停止にもすぐ手が届く位置だ。" },
      { id: "s42b", station: "pc", label: "出力を1点ずつ強制ONし、対象機器の反応を確認する", needs: ["s41", "s42a"], defect: "wrongoutput",
        comment: "図面どおりの機器が反応するか、1点ずつ(Step42)。",
        doneMsg: "ランプ・ブザー・ソレノイド、全て図面どおりの機器が反応した。" },
      { id: "s43", station: "pc", label: "強制ON/OFFを全て解除し、残っていないことを確認する", needs: ["s42b"], defect: "forcedleft", checkpoint: true,
        comment: "強制を残したままエアー投入・自動運転へ進まない(Step43)。",
        doneMsg: "強制設定一覧は空。プログラム制御に戻った。後始末までが仕事だ。" },
    ],
    dangers: [
      { station: "pc", label: "時短のため複数の出力をまとめて強制ONする", level: "mid",
        text: "複数の機器が同時に動いて、どれがどの出力やら分からなくなった",
        lesson: "出力は1点ずつ。どの出力で何が動くか対応を取るのが目的(Step42)。" },
      { station: "machine", label: "装置の中に入ったまま、相方に強制ONしてもらう", level: "big",
        text: "目の前でソレノイドが動いた!あと数センチで挟まれるところだった!",
        lesson: "強制ON前に人が装置内にいないことを必ず確認。エア機器・モーター系の出力は特に危険(Step42)。" },
    ],
    defectPool: [
      { type: "wrongoutput", name: "出力配線の入れ違い(Y10でブザーでなくランプが反応)",
        lesson: "『何かが動く』ではなく『図面どおりの機器が動く』を確認する(Step42)。",
        eventDesc: "Y10を強制ON…図面ではブザーのはず。なのに黄色ランプが光った!",
        correctLabel: "実際に反応した機器を記録し、配線修正箇所としてまとめる",
        correctMsg: "Y10とY11の入れ違いと判明。記録して修正依頼だ。",
        wrongLabel: "何か動いたからヨシ!", wrongLevel: "miss" },
      { type: "forcedleft", name: "強制ONの解除漏れ(1点残留)",
        lesson: "強制状態を残したままエアー投入・手動操作・自動運転へ進まない(Step43)。",
        eventDesc: "強制設定一覧を開くと…Y12が1点、強制ONのまま残っている!",
        correctLabel: "すぐ解除し、残っていた事実を記録する",
        correctMsg: "解除完了。危ない危ない…一覧確認を癖にしよう。",
        wrongLabel: "見なかったことにして一覧を閉じる", wrongLevel: "mid",
        wrongText: "強制ONが残ったまま…次のエアー投入でいきなり機器が動くところだった" },
    ],
  },

  stage8: {
    initial: { sourceOn: true, mainOn: true, cps: { CP1: true, CP2: true, CP3: true } },
    defectCountRange: [0, 2],
    fireAt: "machine",
    steps: [
      { id: "s44a", station: "machine", label: "レギュレータの設定値を確認する",
        comment: "圧力設定のズレは動作不良のもと(Step44)。",
        doneMsg: "0.5MPa、指定どおり。" },
      { id: "s44b", station: "machine", label: "装置内・可動部周辺に人や干渉物がないか確認する",
        comment: "エアー投入時は急にシリンダが動く可能性がある(Step44)。",
        doneMsg: "可動部まわりクリア。工具の置き忘れもなし。" },
      { id: "s45", station: "machine", label: "エアーをゆっくり投入し、漏れ・異音・急動作を確認する", needs: ["s44a", "s44b"], defect: "airleak", checkpoint: true,
        comment: "一気に入れず、状態を見ながらゆっくり(Step45)。",
        doneMsg: "スーッ…とゆっくり昇圧。漏れなし、異音なし、急な動きもなし。" },
      { id: "s46", station: "machine", label: "手動操作で1軸ずつ動かし、対象と方向を確認する", needs: ["s45"], defect: "wrongdir",
        comment: "対象軸と実際に動く機器の一致、動作方向の確認(Step46)。",
        doneMsg: "1軸ずつ前進・後退。対象も方向も指示どおりだ。" },
      { id: "s47", station: "machine", label: "動作中の干渉・配管の突っ張り・停止位置を確認する", needs: ["s46"],
        comment: "センサーの入り、引っかかり、配管・ケーブルの余裕(Step47)。",
        doneMsg: "端のセンサーもきちんと入る。配管にも無理がない。" },
    ],
    dangers: [
      { station: "machine", label: "バルブを全開にして一気にエアーを入れる", level: "big",
        text: "シリンダが猛スピードで飛び出した!治具に激突!",
        lesson: "エアーはゆっくり投入。急投入はシリンダの急動作につながる(Step45)。人が装置内にいたらと思うとゾッとする。" },
      { station: "machine", label: "時短のため2軸同時に動かす", level: "mid",
        text: "2つの軸が干渉コースに入りかけた…冷や汗ものだ",
        lesson: "必ず1軸ずつ。同時に動かすと異常時にどちらを止めるか判断できない(Step46)。" },
    ],
    defectPool: [
      { type: "airleak", name: "継手からのエアー漏れ",
        lesson: "エアー漏れは圧力不足・動作不良のもと。見つけたら即対処(Step45)。",
        eventDesc: "シューーという音…どこかから漏れている!",
        correctLabel: "漏れ箇所を特定して増し締めし、記録する",
        correctMsg: "3番シリンダの継手だった。増し締めで止まった。記録OK。",
        wrongLabel: "そのうち馴染んで止まるだろう", wrongLevel: "miss" },
      { type: "wrongdir", name: "電磁弁配線の逆(前進指令で後退する)",
        lesson: "動作方向が指示と違えば配線・設定を直す。運用でごまかさない(Step46)。",
        eventDesc: "前進ボタンを押した…のにシリンダが後退した!逆だ!",
        correctLabel: "電磁弁の配線を疑い、記録する",
        correctMsg: "電磁弁のa/b配線が逆と判明。記録して修正依頼。",
        wrongLabel: "『このボタンは逆』と覚えておけばいいや", wrongLevel: "mid",
        wrongText: "『覚えでカバー』は次に触る人が事故る。装置は正しく直すのが筋だ" },
    ],
  },

  stage9: {
    initial: { sourceOn: true, mainOn: true, cps: { CP1: true, CP2: true, CP3: true } },
    defectCountRange: [0, 2],
    fireAt: "machine",
    steps: [
      { id: "s49", station: "machine", label: "各軸が原点復帰できる位置か・干渉物がないか確認する",
        comment: "原点復帰動作中の干渉を先に潰す(Step49)。",
        doneMsg: "各軸とも復帰可能な位置。動作範囲内に人・工具・治具なし。" },
      { id: "s48", station: "machine", label: "低速で目的位置まで動かし、ポイントを登録する", needs: ["s49"], defect: "interfere",
        comment: "低速で、目視で干渉がないことを確認しながら(Step48)。",
        doneMsg: "受け渡し位置・待機位置を登録。再生しても干渉なし。" },
      { id: "s50", station: "machine", label: "各軸を1軸ずつ個別に原点復帰させる(初回は低速)", needs: ["s49"], defect: "wrongdirhome",
        comment: "動作方向・速度・停止動作を1軸ずつ確認(Step50)。",
        doneMsg: "全軸、正しい方向へ低速で復帰。異常なし。" },
      { id: "s51", station: "machine", label: "原点復帰の方向と停止位置を確認する", needs: ["s50"],
        comment: "原点センサ検出後、決められた位置で止まるか(Step51)。",
        doneMsg: "設定どおりの方式で動作し、原点位置でピタリと停止。" },
      { id: "s52", station: "pc", label: "各軸の原点完了信号がONするか確認する", needs: ["s50"],
        comment: "機械が止まっていても信号が立たなければ完了ではない(Step52)。",
        doneMsg: "各軸の原点完了信号ON。画面表示とも一致。" },
      { id: "s53", station: "machine", label: "全原点復帰を実行し、順序とインターロックを確認する", needs: ["s50", "s52"], checkpoint: true,
        comment: "決められた順番で動き、干渉防止が働くか(Step53〜54)。",
        doneMsg: "Z軸上昇→X軸→ロボットの順で復帰。インターロックも正常だ。" },
      { id: "s55", station: "pc", label: "全原点完了信号と各軸の状態を最終確認する", needs: ["s53"],
        comment: "一部の完了だけで全原点完了と判断しない(Step55)。",
        doneMsg: "全軸の個別完了+装置全体の全原点完了信号ON。文句なし!" },
    ],
    dangers: [
      { station: "machine", label: "個別確認を飛ばして、いきなり全原点復帰を実行する", level: "big",
        text: "ロボットが治具に一直線!ガシャン!!",
        lesson: "最初から全原点復帰を行わない。各軸を個別に低速で確認してから(Step49〜50)。" },
      { station: "machine", label: "高速モードのままティーチングする", level: "mid",
        text: "行き過ぎて危うく激突…手が汗でびっしょりだ",
        lesson: "ティーチングは低速で、目視で干渉を確認しながら(Step48)。" },
    ],
    defectPool: [
      { type: "interfere", name: "登録ポイントが治具と干渉",
        lesson: "干渉は『ワークを持った状態』も考えて判断する(Step48)。",
        eventDesc: "登録した位置を再生…アームが治具スレスレを通っていく!",
        correctLabel: "ポイントデータを修正し、記録する",
        correctMsg: "経由点を追加して安全な軌道に修正。記録OK。",
        wrongLabel: "ギリギリ通っているからヨシ!", wrongLevel: "mid",
        wrongText: "ワークを掴んだら確実に当たる軌道だった…想像力が足りなかった" },
      { type: "wrongdirhome", name: "原点復帰方向の設定ミス(逆走)",
        lesson: "想定外の方向へ動いたら、ただちに停止(Step50)。",
        eventDesc: "原点復帰スタート…あれ?原点と逆の方向に動いている!",
        correctLabel: "すぐ停止し、原点復帰パラメータを確認・記録する",
        correctMsg: "即停止。復帰方向のパラメータが逆だった。記録して修正。",
        wrongLabel: "そのうち折り返して戻ってくるだろう", wrongLevel: "big",
        wrongText: "軸がそのまま機械端に突っ込んだ!リミットを突き破る音がした!" },
    ],
  },

  stage10: {
    initial: { sourceOn: true, mainOn: true, cps: { CP1: true, CP2: true, CP3: true } },
    defectCountRange: [0, 2],
    fireAt: "machine",
    steps: [
      { id: "s56", station: "machine", label: "対象ユニット周辺の安全を確認し、声掛けする",
        comment: "動作前の周囲確認と声掛け(Step56)。",
        doneMsg: "『動かしまーす!』周囲よし、障害物なし。" },
      { id: "s57", station: "panel", label: "タッチパネルで対象動作を選択し、実行前に再確認する",
        comment: "選択した動作と対象ユニットの一致を実行前に確認(Step57)。",
        doneMsg: "『供給ユニット・1サイクル』を選択。対象も間違いない。" },
      { id: "s58", station: "pc", label: "動作開始条件が成立しているか確認する", needs: ["s57"],
        comment: "成立していない条件は一つずつ確認(Step58)。",
        doneMsg: "開始条件、全て成立している。" },
      { id: "s59", station: "machine", label: "1動作ずつ実行し、方向・順序・停止位置を確認する", needs: ["s56", "s58"], defect: "stoppos",
        comment: "複数動作を同時に実行しない(Step59〜60)。",
        doneMsg: "供給→クランプ→加工…1動作ずつ、方向も順序も指示どおり。" },
      { id: "s62", station: "machine", label: "動作完了センサーがONするか確認する", needs: ["s59"], defect: "sensoroff",
        comment: "センサー未検出のまま次動作へ進めない(Step62)。",
        doneMsg: "各動作の完了センサー、きちんとONしている。" },
      { id: "s64", station: "machine", label: "動作後のワーク・治具位置を確認する", needs: ["s59"],
        comment: "位置ズレは次動作の干渉・不良につながる(Step64)。",
        doneMsg: "ワークは治具の真ん中にピタリ。浮きもなし。" },
      { id: "s65", station: "desk", label: "単動作の確認結果を記録する", needs: ["s59"],
        comment: "異常があった場合は原因と対処も記録(Step65)。",
        doneMsg: "確認済み動作を記録。異常箇所もまとめた。" },
      { id: "s66", station: "panel", label: "自動起動で連続運転し、タクトと安定性を確認する", needs: ["s62", "s64", "s65"], defect: "chokotei", checkpoint: true,
        comment: "複数サイクルの安定運転とタクトタイム(Step66)。",
        doneMsg: "10サイクル連続、タクト12秒で安定!装置立ち上げ完了だ!!" },
    ],
    dangers: [
      { station: "pc", label: "成立しない開始条件を強制ONして無理やり起動する", level: "big",
        text: "条件を無視して動いた装置が、前の動作のワークと衝突した!",
        lesson: "条件を無理に強制ONしない(Step58)。開始条件には装置とワークを守る意味がある。" },
      { station: "machine", label: "連続運転中に、装置内のワークのズレを手で直す", level: "big",
        text: "動いている装置に手を入れた!クランプが目の前で閉じた!間一髪!",
        lesson: "チョコ停対応でも必ず装置を止めてから。『ちょっとだけ』が重大事故のもと(Step66)。" },
    ],
    defectPool: [
      { type: "stoppos", name: "停止位置のズレ(次動作と干渉)",
        lesson: "停止位置ズレは次動作の干渉につながるため必ず確認(Step60)。",
        eventDesc: "動作は完了…だが停止位置が数ミリずれている気がする",
        correctLabel: "ズレを測って記録し、次動作との干渉を確認する",
        correctMsg: "3mmのズレを確認。次動作と干渉する寸法だった。記録して調整依頼。",
        wrongLabel: "数ミリなら誤差の範囲だろう", wrongLevel: "miss" },
      { type: "sensoroff", name: "完了センサーの未検出(感度不足)",
        lesson: "センサー未検出のまま次動作へ進めない(Step62)。",
        eventDesc: "動作は終わった…のに完了センサーがONしない!",
        correctLabel: "センサーの位置・感度を確認して記録する",
        correctMsg: "検出位置が1mm遠かった。位置調整して検出OK。記録した。",
        wrongLabel: "動作は終わってるんだから次へ進めてしまう", wrongLevel: "mid",
        wrongText: "未検出のまま進むと、装置は『前の動作が終わっていない』ままだ。自動運転で必ず止まるぞ" },
      { type: "chokotei", name: "連続運転中のチョコ停(ワーク引っかかり)",
        lesson: "チョコ停はエラー履歴から原因特定→対策(Step66)。再起動連打は解決ではない。",
        eventDesc: "自動運転中…3サイクル目で装置が止まった!チョコ停だ!",
        correctLabel: "エラー履歴から原因を特定し、記録する",
        correctMsg: "供給シュートでワークが引っかかっていた。ガイドの調整を記録。",
        wrongLabel: "もう一度スタートを押して様子を見る", wrongLevel: "mid",
        wrongText: "また3サイクル目で止まった。原因を見ずに再起動しても同じことの繰り返しだ" },
    ],
  },
};
